#!/bin/bash
#
# bash file that isolates the time-series of a specific probe so that it can be plotted
# easily and remotely using gnuplot. See usage and arguments below.
# eg: for the y coordinate of thee probe with id 9 of the file U 
# (that contains 3 component vectors), execute:
# ./probeProcess U 9 2 3
#

echo " * =================================================================================== *"
echo " | == Give 4 arguments   1: filename                                                == |"
echo " | == 		         2: probe number (probe ID)                                 == |"
echo " | == 		         3: coord number (1 for x, 2 for y,3 for z)                 == |"
echo " | == 		         4: tensor size  (1 for scalar, 3 for vector, 6 for tensor) == |"
echo " * =================================================================================== *"

var=$(($4*$2+1+$3))
filename=probe_"$1"_"$2"_"$3"
j=$(sed "$(($2+1))q;d" $1)

awk -v variab="$var" '{print $1 " " $variab}' $1 >>  $filename

sed -i '/#/d' $filename
sed -i 's/(/ /g' $filename
sed -i 's/)/ /g' $filename
sed -i "1s/^/$j \n/" $filename

echo "Done writing file $filename."
