#!/bin/bash
# This code takes as an argument the current log.pimpleFoam file. It outputs the hours needed
# to finish the simulation, based on the endTime in controlDict and on the time that has 
# elapsed so far. It creates a hidden file that it then deletes named .temp .
# Feel free to add it in your .bashrc. It's handy.

if [ -f .temp ] 
then
	echo " File called .temp already exists, I'm exiting because I don't want to overwrite"
	return
fi

if [[ $1 == "" ]] 
then
	cat log.pimpleFoam >.temp
else
	cat $1 >.temp
fi

nProcs=$(grep "^nProcs" .temp | awk '{print $3}')
nbIter=$(grep "^Time = " .temp | wc -l | awk '{print $1}')
startTime=$(grep "^Time = " .temp | head -1 |awk '{print $3}')
latestTime=$(grep "^Time = " .temp | tail -n 1 |awk '{print $3}')
execTime=$(grep "^ExecutionTime" .temp | tail -n 1 | awk '{print $3}')
endTime=$(grep "^endTime" system/controlDict | tail -n 1 | awk '{print $2}' | tr -d ';')
execTimeHours=$(echo $execTime\/3600 | bc -l )
execTimeMins=$(echo $execTime\/60 | bc -l )

temp1=$(echo $latestTime\-$startTime | bc  )
execTimePerSecond=$(echo $execTime\/3600\/$temp1 | bc -l )
temp2=$(echo $endTime\-$latestTime | bc )
totalHoursNeeded=$(echo $temp2\*$execTimePerSecond | bc -l )

echo "Number of processors " $nProcs

echo "Number of iterations " $nbIter

echo "Start Time (sec)   = " $startTime  

echo "Latest Time (sec)  = " $latestTime    

echo -n "Elapse Time (hrs)  = "  
echo $execTimeHours | cut -b1-5

echo -n "Elapse Time (mins) = "  
echo  $execTimeMins | cut -b1-5

echo -n "Elapse Time (sec)  = "  
echo  $execTime | cut -b1-5

echo  "End Time (sec)     = " $endTime 

echo -n "Hours executed so far to go from " $startTime " to " $latestTime ": "
echo -n $execTimeHours |	cut -b1-5

echo -n "Hours needed to go from " $latestTime " to " $endTime ": " 
echo  $totalHoursNeeded |	cut -b1-5

rm .temp

