#!/bin/bash

# ===================== SLURM SETTINGS ========================= #
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=20G
#SBATCH --time=00:20:00
#SBATCH --job-name=insert_name
#SBATCH --mail-user=wtvr1234@eng.ox.ac.uk
#SBATCH --mail-type=ALL
#SBATCH --partition=interactive

# ======================= LOAD MODULES ========================= #
#cd "${0%/*}" || exit                     # Run from this directory
module load OpenFOAM/v2006-foss-2020a
source $FOAM_BASH
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# ====================  RUN THE PRE PROCESS =================== #

blockMesh                > log.blockMesh
snappyHexMesh -overwrite > log.snappyHexMesh
checkMesh 				 > log.checkMesh
foamToEnsight 			 > log.foamToEnsight
cp -r 0.org 0
decomposePar             > log.decomposePar 

